alpha: 0.9
batch_size: 4
beta: 0.999
bias_lr_factor: 2.0
cmt_depth: 4
dataset_name: MSVD
distributed: false
eval_period: 1
gamma: 0.1
img_aug: true
img_size: !!python/tuple
- 384
- 128
local_rank: 0
log_period: 100
loss_names: TAL+sr0.3_tau0.015_margin0.1_n0.2
lr: 1.0e-05
lr_factor: 5.0
lrscheduler: cosine
margin: 0.1
masked_token_rate: 0.8
masked_token_unchanged_rate: 0.1
milestones: !!python/tuple
- 20
- 50
momentum: 0.9
name: RDE
noisy_file: ./noiseindex/MSVD_0.2.npy
noisy_rate: 0.2
num_epoch: 60
num_instance: 4
num_workers: 1
optimizer: Adam
output_dir: run_logs/MSVD/20250315_210105_RDE_TAL+sr0.3_tau0.015_margin0.1_n0.2
power: 0.9
pretrain_choice: ViT-B/16
resume: false
resume_ckpt_file: ''
root_dir: ./datas
sampler: random
select_ratio: 0.3
stride_size: 16
target_lr: 0
tau: 0.015
temperature: 0.02
test_batch_size: 512
text_length: 77
training: true
txt_aug: true
val_dataset: test
video_frame_rate: 3
vocab_size: 49408
warmup_epochs: 5
warmup_factor: 0.1
warmup_method: linear
weight_decay: 4.0e-05
weight_decay_bias: 0.0
